"""
Tests for the Phase 3 Step 5 loader changes.

These run against a real DuckDB connection and real files, because every one of
them is about behaviour that only shows up when the data actually moves:
whether a footer row reaches the type sniffer, whether a bad cell nulls or
stops, whether the spec's row numbers survive the trip.

The last group drives a load entirely from an IngestSpec. That is the first
point in Phase 3 where a spec produces a table.
"""

from __future__ import annotations

import datetime as dt

import pytest
from openpyxl import Workbook

from backend.engine import workspace
from backend.engine.util import db

from backend.engine.ingest import excel as excel_mod
from backend.engine.ingest.csv_loader import (
    LoadRefused,
    LoadResult,
    load_csv,
    validate_on_error,
)
from backend.engine.ingest.excel import load_excel
from backend.engine.ingest.spec import ColumnSpec, IngestSpec


WORKSPACE = "step5_test"


@pytest.fixture
def con():
    """
    A workspace-scoped connection, not a bare duckdb.connect().

    Every loader calls db.register_dataset on success, and that writes to
    _agent_datasets -- a table only db.connect() creates. A bare connection
    loads the data correctly and then falls over on the very next line, which
    is exactly what happened the first time these tests met the real db module.

    Its own workspace, like tests/test_phase2.py uses phase2_test, so nothing
    loaded in 'local' is touched.
    """
    workspace.reset(WORKSPACE)
    c = db.connect(WORKSPACE)
    try:
        yield c
    finally:
        c.close()
        workspace.reset(WORKSPACE)


@pytest.fixture
def dirty_csv(tmp_path):
    """20 clean rows, two with bad values, and a totals footer."""
    p = tmp_path / "dirty.csv"
    lines = ["id,units,price"]
    lines += [f"{i},{i},{i}.5" for i in range(1, 21)]
    lines += ["21,N/A,9.5", "22,oops,8.5", "TOTAL,,"]
    p.write_text("\n".join(lines) + "\n")
    return str(p)


@pytest.fixture
def messy_xlsx(tmp_path):
    """
    Title, blanks, header at row 5, data from row 6, totals row at the end.
    The shape of tests/fixtures/messy_headers.xlsx.
    """
    wb = Workbook()
    ws = wb.active
    ws.title = "Report"
    ws["A1"] = "Quarterly Report"
    ws["A3"] = "generated by finance"
    ws["A5"], ws["B5"], ws["C5"] = "order_id", "units", "when"
    for i in range(6, 16):
        ws.cell(row=i, column=1, value=f"A{i - 5}")
        ws.cell(row=i, column=2, value=i - 5)
        ws.cell(row=i, column=3, value=dt.datetime(2024, 1, 1))
    ws.cell(row=16, column=1, value="TOTAL")
    ws.cell(row=16, column=2, value=55)
    path = tmp_path / "messy.xlsx"
    wb.save(path)
    return str(path)


# --------------------------------------------------------------------------
# on_error
# --------------------------------------------------------------------------

def test_on_error_defaults_to_stop():
    import inspect

    for fn in (load_csv, load_excel):
        assert inspect.signature(fn).parameters["on_error"].default == "stop"


def test_an_unknown_on_error_mode_is_refused():
    with pytest.raises(LoadRefused) as exc:
        validate_on_error("skip")
    assert "NEXT STEP" in str(exc.value)


def test_csv_stop_refuses_a_value_that_will_not_convert(con, dirty_csv):
    with pytest.raises(LoadRefused) as exc:
        load_csv(con, dirty_csv, "d", dtypes={"units": "BIGINT"}, footer_skip_rows=1)
    assert "NEXT STEP" in str(exc.value)


def test_csv_null_counts_per_column_and_keeps_the_rows(con, dirty_csv):
    r = load_csv(
        con,
        dirty_csv,
        "d",
        on_error="null",
        footer_skip_rows=1,
        dtypes={"units": "BIGINT", "price": "DOUBLE"},
    )
    assert r.coercion_failures == {"units": 1}
    assert r.row_count == 22
    assert con.execute('SELECT units FROM d WHERE id=22').fetchone()[0] is None


def test_na_values_are_not_counted_as_coercion_failures(con, dirty_csv):
    """'N/A' is a declared null, not a value that failed to convert."""
    r = load_csv(
        con, dirty_csv, "d", on_error="null", footer_skip_rows=1,
        na_values=["N/A"], dtypes={"units": "BIGINT"},
    )
    assert r.coercion_failures.get("units", 0) == 1  # 'oops' only
    assert con.execute('SELECT units FROM d WHERE id=21').fetchone()[0] is None


def test_excel_stop_names_the_row_and_column(con, tmp_path):
    wb = Workbook()
    ws = wb.active
    ws.title = "S"
    ws.append(["id", "units"])
    for i in range(1, 12):
        ws.append([i, i])
    ws.append([12, "oops"])
    p = tmp_path / "bad.xlsx"
    wb.save(p)

    with pytest.raises(LoadRefused) as exc:
        load_excel(con, str(p), "b", sheet="S", inference_rows=5)
    msg = str(exc.value)
    assert "row 13" in msg
    assert "'units'" in msg
    assert "on_error='null'" in msg


def test_excel_null_counts_per_column_and_keeps_the_rows(con, tmp_path):
    wb = Workbook()
    ws = wb.active
    ws.title = "S"
    ws.append(["id", "units"])
    for i in range(1, 12):
        ws.append([i, i])
    ws.append([12, "oops"])
    p = tmp_path / "bad.xlsx"
    wb.save(p)

    r = load_excel(con, str(p), "b", sheet="S", inference_rows=5, on_error="null")
    assert r.coercion_failures == {"units": 1}
    assert r.row_count == 12
    assert con.execute('SELECT units FROM b WHERE id=12').fetchone()[0] is None


def test_coercion_failures_are_reported_in_the_summary(con, dirty_csv):
    r = load_csv(
        con, dirty_csv, "d", on_error="null", footer_skip_rows=1,
        dtypes={"units": "BIGINT"},
    )
    text = r.summary()
    assert "did not fit their column" in text
    assert "units (1)" in text
    assert "rows were kept" in text


def test_a_clean_load_reports_no_coercion_note(con, tmp_path):
    p = tmp_path / "clean.csv"
    p.write_text("id,units\n1,1\n2,2\n")
    r = load_csv(con, str(p), "c", on_error="null")
    assert r.coercion_failures == {}
    assert "did not fit" not in r.summary()
    assert r.coercion_total == 0


def test_the_fixture_gives_a_workspace_connection(con, tmp_path):
    """
    Guards the bug this file shipped with once. A bare duckdb.connect() loads
    the data correctly and then falls over registering it, so twelve tests fail
    on a catalog error that says nothing about the loaders. This fails first
    and says what is actually wrong.
    """
    con.execute(f"SELECT count(*) FROM {db.METADATA_TABLE}")

    p = tmp_path / "one.csv"
    p.write_text("id\n1\n")
    load_csv(con, str(p), "reg")
    assert con.execute(
        f"SELECT count(*) FROM {db.METADATA_TABLE} WHERE dataset_name='reg'"
    ).fetchone()[0] == 1


def test_an_empty_na_values_list_means_no_token_is_null(con, tmp_path):
    """
    DuckDB rejects nullstr=[] outright -- "requires a non-empty list of
    possible null strings" -- so an empty list has to mean the option is
    omitted. It is a legitimate way to say a literal 'N/A' is data.
    """
    p = tmp_path / "tok.csv"
    p.write_text("id,region\n1,N/A\n2,North\n")

    kept = load_csv(con, str(p), "kept", na_values=[])
    assert kept.row_count == 2
    assert con.execute("SELECT region FROM kept WHERE id=1").fetchone()[0] == "N/A"

    nulled = load_csv(con, str(p), "nulled", na_values=["N/A"])
    assert con.execute("SELECT region FROM nulled WHERE id=1").fetchone()[0] is None


def test_load_result_defaults_keep_old_callers_working():
    r = LoadResult(dataset_name="x", row_count=1, column_count=1)
    assert r.coercion_failures == {}
    assert r.coercion_total == 0


# --------------------------------------------------------------------------
# footer_skip_rows
# --------------------------------------------------------------------------

def test_csv_footer_rows_are_dropped(con, dirty_csv):
    r = load_csv(con, dirty_csv, "d", on_error="null", footer_skip_rows=1)
    assert r.row_count == 22
    assert con.execute("SELECT count(*) FROM d WHERE id='TOTAL'").fetchone()[0] == 0


def test_csv_footer_skip_keeps_the_first_rows_not_arbitrary_ones(con, tmp_path):
    """
    read_csv has no skipfooter, so this is done with count(*) then LIMIT. That
    is only correct because a scan preserves file order -- checked here at
    threads=8, where a parallel scan would show up.
    """
    con.execute("SET threads=8")
    p = tmp_path / "ord.csv"
    p.write_text("id\n" + "".join(f"{i}\n" for i in range(1, 5001)) + "TOTAL\n")

    load_csv(con, str(p), "o", footer_skip_rows=1, dtypes={"id": "VARCHAR"})
    kept = [r[0] for r in con.execute("SELECT id FROM o").fetchall()]
    assert kept == [str(i) for i in range(1, 5001)]


def test_excel_footer_rows_are_dropped(con, messy_xlsx):
    r = load_excel(
        con, messy_xlsx, "m", sheet="Report", header_rows=5,
        names=["order_id", "units", "when"], footer_skip_rows=1,
    )
    assert r.row_count == 10
    assert con.execute(
        "SELECT count(*) FROM m WHERE order_id='TOTAL'"
    ).fetchone()[0] == 0


def test_excel_footer_trim_happens_before_type_inference(con, messy_xlsx):
    """
    The totals row would drag order_id to VARCHAR if the sniffer saw it. The
    deque drops it before inference, so the types describe the data.
    """
    r = load_excel(
        con, messy_xlsx, "m", sheet="Report", header_rows=5,
        names=["order_id", "units", "when"], footer_skip_rows=1,
    )
    types = dict(r.columns)
    assert types["units"] == "BIGINT"
    assert types["when"] == "TIMESTAMP"


def test_negative_footer_skip_is_refused(con, dirty_csv):
    with pytest.raises(LoadRefused) as exc:
        load_csv(con, dirty_csv, "d", footer_skip_rows=-1)
    assert "cannot be negative" in str(exc.value)


def test_footer_skip_larger_than_the_file_is_refused(con, tmp_path):
    p = tmp_path / "tiny.csv"
    p.write_text("id\n1\n2\n")
    with pytest.raises(LoadRefused) as exc:
        load_csv(con, str(p), "t", footer_skip_rows=99, dtypes={"id": "VARCHAR"})
    assert "only 2 data row" in str(exc.value)


def test_excel_footer_skip_that_eats_every_row_is_refused(con, messy_xlsx):
    with pytest.raises(LoadRefused) as exc:
        load_excel(
            con, messy_xlsx, "m", sheet="Report", header_rows=5,
            names=["order_id", "units", "when"], footer_skip_rows=99,
        )
    assert "no data rows" in str(exc.value)


# --------------------------------------------------------------------------
# na_values on Excel -- the parity fix
# --------------------------------------------------------------------------

def test_excel_na_values_are_applied_before_type_inference(con, tmp_path):
    """
    Without this, a column of integers containing 'N/A' is VARCHAR -- F5. The
    token has to become None before the sniffer sees the column.
    """
    wb = Workbook()
    ws = wb.active
    ws.title = "S"
    ws.append(["id", "units"])
    ws.append([1, 10])
    ws.append([2, "N/A"])
    ws.append([3, 30])
    p = tmp_path / "na.xlsx"
    wb.save(p)

    plain = load_excel(con, str(p), "p", sheet="S")
    assert dict(plain.columns)["units"] == "VARCHAR"

    with_na = load_excel(con, str(p), "q", sheet="S", na_values=["N/A"])
    assert dict(with_na.columns)["units"] == "BIGINT"
    assert con.execute("SELECT units FROM q WHERE id=2").fetchone()[0] is None


def test_excel_na_values_only_match_strings(con, tmp_path):
    """A numeric 0 is not a null token however the token list is written."""
    wb = Workbook()
    ws = wb.active
    ws.title = "S"
    ws.append(["id", "units"])
    ws.append([1, 0])
    ws.append([2, 5])
    p = tmp_path / "zero.xlsx"
    wb.save(p)

    r = load_excel(con, str(p), "z", sheet="S", na_values=["0"])
    assert con.execute("SELECT units FROM z WHERE id=1").fetchone()[0] == 0
    assert r.coercion_failures == {}


# --------------------------------------------------------------------------
# excel.merged_ranges is gone
# --------------------------------------------------------------------------

def test_excel_no_longer_exports_merged_ranges():
    """
    One name, one implementation. If this passes while something still calls
    excel.merged_ranges, that caller raises AttributeError loudly rather than
    reading the wrong sheet quietly.
    """
    assert not hasattr(excel_mod, "merged_ranges")


# --------------------------------------------------------------------------
# a spec driving a real load -- the first end-to-end run
# --------------------------------------------------------------------------

def test_a_spec_loads_the_messy_workbook_without_eating_the_title(con, messy_xlsx):
    """
    Header at row 5, data from row 6. The spec says header_rows=[5]; the loader
    must be told 5, not 1. Getting that wrong loads the title as data and types
    every column VARCHAR -- F12 producing F5.
    """
    spec = IngestSpec(
        path=messy_xlsx,
        source_type="excel",
        dataset_name="messy",
        sheet="Report",
        header_rows=[5],
        data_start_row=6,
        footer_skip_rows=1,
        columns=[
            ColumnSpec(source_name="order_id", target_name="order_id"),
            ColumnSpec(source_name="units", target_name="units"),
            ColumnSpec(source_name="when", target_name="when"),
        ],
    )
    assert len(spec.header_rows) == 1
    assert spec.loader_header_rows == 5

    result = load_excel(con, messy_xlsx, **spec.to_loader_kwargs(load_excel))

    assert result.row_count == 10
    assert dict(result.columns)["units"] == "BIGINT"
    first = con.execute(
        "SELECT order_id FROM messy ORDER BY units LIMIT 1"
    ).fetchone()[0]
    assert first == "A1"
    assert con.execute(
        "SELECT count(*) FROM messy WHERE order_id LIKE 'Quarterly%'"
    ).fetchone()[0] == 0


def test_the_spec_bridge_no_longer_refuses_na_values_or_footer_skip():
    """
    Step 3 left to_loader_kwargs raising SpecNotSupported for both fields.
    Adding them to the loaders is what makes that stop -- and this is the test
    that says the to-do list is done.
    """
    spec = IngestSpec(
        path="x.xlsx",
        source_type="excel",
        dataset_name="x",
        sheet="S",
        header_rows=[1],
        data_start_row=2,
        na_values=["N/A"],
        footer_skip_rows=2,
        columns=[ColumnSpec(source_name="Units", target_name="units")],
    )
    kwargs = spec.to_loader_kwargs(load_excel)
    assert kwargs["na_values"] == ["N/A"]
    assert kwargs["footer_skip_rows"] == 2

    csv_spec = IngestSpec(
        path="x.csv",
        source_type="csv",
        dataset_name="x",
        header_rows=[1],
        data_start_row=2,
        na_values=["-"],
        footer_skip_rows=1,
        columns=[ColumnSpec(source_name="Units", target_name="units")],
    )
    kwargs = csv_spec.to_loader_kwargs(load_csv)
    assert kwargs["footer_skip_rows"] == 1


# --- the tokens read as NULL are said (Cleanup Step 12, RF-O4) ----------------------------------

def test_the_load_reply_names_each_token_it_read_as_null(con, tmp_path):
    """Retail: rating's 8,069 'NA' and 5,353 '-' became NULL and the reply said nothing."""
    from backend.engine.ingest.csv_loader import load_csv
    p = tmp_path / "tokens.csv"
    p.write_text("id,rating,city\n1,4,Pune\n2,NA,Pune\n3,-,-\n4,n/a,Pune\n5,,Pune\n6,-,Pune\n")
    r = load_csv(con, p, "tokens")
    assert r.null_tokens == {"rating": {"-": 2, "NA": 1}, "city": {"-": 1}}
    text = r.summary()
    assert "rating ('-' 2, 'NA' 1)" in text and "city ('-' 1)" in text
    assert "na_values=[]" in text


def test_no_token_means_no_note(con, tmp_path):
    from backend.engine.ingest.csv_loader import load_csv
    p = tmp_path / "clean.csv"
    p.write_text("id,rating\n1,4\n2,\n")
    r = load_csv(con, p, "clean_tokens")
    assert r.null_tokens == {} and "read as NULL" not in r.summary()
