"""
Where a confirmed contract lives, and how it stops being current.

Two homes, and the split matters.

**The workspace database is authoritative.** `_agent_contracts` holds every
contract ever confirmed for every dataset, as an append-only log: confirming a
new one writes a new row and closes the previous one rather than overwriting
it. That is SCD2 -- Slowly Changing Dimension Type 2, standard warehouse
vocabulary -- with `valid_from`, `valid_to` and `is_current` doing exactly what
they do in any warehouse dimension. Locked decision 18 wants the ledger inside
every report; a contract that can be edited in place cannot support that,
because "what did we agree, and when did it change" stops having an answer the
first time someone changes their mind.

**`docs/contracts/<dataset>.yaml` is an export.** Definitions belong in version
control, which is where the semantic-layer tools put them (dbt MetricFlow,
Cube, LookML) and what makes a number in a report reviewable in a pull request
rather than only inside a database file. It is regenerated on every confirm and
never read back. If the two disagree, the database is right and the file is
stale -- so it carries a header saying so.

Three rules the store enforces rather than documents.

**A provisional contract cannot be stored.** `is_confirmable` is checked here
as well as in the model, because this is the boundary where a guess would stop
being a guess.

**A contract with no binding cannot be stored.** Without it, Step 3 can never
answer whether the agreement still holds -- there is nothing to compare the
table against. A contract is allowed to exist unbound (it has to be readable
back on a machine that never loaded the table); it is not allowed to be
*confirmed* unbound.

**Confirming the same contract twice does not write a second version.**
Versions are for changes. A history where half the entries are re-confirmations
of an unchanged document is a history nobody reads.
"""

from __future__ import annotations

from backend.engine.util import db

import json
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

from backend.engine.config import PROJECT_ROOT
from backend.engine.contract import ContractRefused
from backend.engine.contract.dataset_contract import DatasetContract
from backend.engine.contract.refusals import Reason, Refusal

# Underscore-prefixed, so evidence._user_tables and any list_datasets treat it
# as bookkeeping rather than as something a person loaded.
CONTRACT_TABLE = "_agent_contracts"

# Where the git-visible copies go. From PROJECT_ROOT, not the working directory: it was
# Path("docs/contracts") and landed wherever the process was started, the one path in this
# engine config.py:74 did not cover (C94). A workspace other than the default exports into a
# subdirectory named for it -- see contract/tools.workspace_export_root.
EXPORT_DIR = PROJECT_ROOT / "docs" / "contracts"

_EXPORT_HEADER = """\
# GENERATED BY confirm_dataset_contract -- DO NOT EDIT.
#
# The authoritative copy lives in the workspace database ({table}).
# This file is rewritten on every confirmation and is never read back, so an
# edit here changes nothing and will be overwritten. To change the contract,
# call propose_dataset_contract with the correction and confirm the result.
"""


@dataclass
class StoredContract:
    """One row of the log."""

    contract: DatasetContract
    version: int
    fingerprint: str
    row_count: int
    confirmed_at: datetime
    valid_from: datetime
    valid_to: datetime | None
    is_current: bool

    @property
    def dataset_name(self) -> str:
        return self.contract.dataset_name

    def line(self) -> str:
        """One line of history, for get_workflow_state."""
        span = (
            f"{self.valid_from:%Y-%m-%d %H:%M} -> "
            f"{'now' if self.is_current else format(self.valid_to, '%Y-%m-%d %H:%M')}"
        )
        return (
            f"v{self.version}  {span}  {self.fingerprint}  "
            f"{self.row_count:,} rows  {self.contract.grain}"
        )


# Fields compared when working out what a new version changed. `version` and
# `confirmed_at` are written by the store, so they always differ and would
# swamp the answer.
_TRACKED = (
    "grain",
    "primary_key",
    "date_column",
    "analysis_window",
    "dimensions",
    "known_exclusions",
    "expectations",
    "caveats",
    "measured_caveats",
    "bound_to",
    "missing_values",
    "excluded_columns",
    "foreign_keys",
    "domains",
)


def changed_fields(new: DatasetContract, old: DatasetContract) -> list[str]:
    """
    Which parts of a contract differ, as field paths.

    Written after reading a rendered history and finding it useless: two
    versions whose grain and fingerprint match print identical lines, and the
    only thing that had actually changed -- a measure definition -- was
    nowhere in the output. A log that records that something changed without
    recording what is a log nobody consults twice.
    """
    a = json.loads(new.model_dump_json())
    b = json.loads(old.model_dump_json())
    changed = [f for f in _TRACKED if a.get(f) != b.get(f)]

    new_measures = {m.name: m for m in new.measures}
    old_measures = {m.name: m for m in old.measures}
    for name in sorted(set(new_measures) - set(old_measures)):
        changed.append(f"measures[{name}] (added)")
    for name in sorted(set(old_measures) - set(new_measures)):
        changed.append(f"measures[{name}] (removed)")
    for name in sorted(set(new_measures) & set(old_measures)):
        for attr in ("agg", "definition", "unit"):
            if getattr(new_measures[name], attr) != getattr(old_measures[name], attr):
                changed.append(f"measures[{name}].{attr}")
    return changed


def _ensure_table(con) -> None:
    """
    Create the log if it is not there.

    Lazily rather than in db.connect(), so nothing in the ingest layer has to
    know that contracts exist. The cost is one CREATE TABLE IF NOT EXISTS per
    call, which DuckDB answers from its catalog.
    """
    db.create_if_missing(
        con,
        f"""
        CREATE TABLE IF NOT EXISTS {CONTRACT_TABLE} (
            dataset_name  VARCHAR   NOT NULL,
            version       INTEGER   NOT NULL,
            contract_json VARCHAR   NOT NULL,
            fingerprint   VARCHAR   NOT NULL,
            row_count     BIGINT    NOT NULL,
            grain         VARCHAR   NOT NULL,
            confirmed_at  TIMESTAMP NOT NULL,
            valid_from    TIMESTAMP NOT NULL,
            valid_to      TIMESTAMP,
            is_current    BOOLEAN   NOT NULL
        )
        """
    )


def _comparable(contract: DatasetContract) -> str:
    """
    The contract without its bookkeeping, for deciding whether it changed.

    `version` and `confirmed_at` are written BY the store, so including them
    would make every contract differ from the one before it and defeat the
    check entirely.
    """
    payload: dict[str, Any] = json.loads(contract.model_dump_json())
    payload.pop("version", None)
    payload.pop("confirmed_at", None)
    return json.dumps(payload, sort_keys=True)


def _row_to_stored(row) -> StoredContract:
    (
        _name, version, payload, fingerprint, row_count, _grain,
        confirmed_at, valid_from, valid_to, is_current,
    ) = row
    return StoredContract(
        contract=DatasetContract.model_validate_json(payload),
        version=version,
        fingerprint=fingerprint,
        row_count=row_count,
        confirmed_at=confirmed_at,
        valid_from=valid_from,
        valid_to=valid_to,
        is_current=is_current,
    )


_SELECT = f"""
    SELECT dataset_name, version, contract_json, fingerprint, row_count, grain,
           confirmed_at, valid_from, valid_to, is_current
    FROM {CONTRACT_TABLE}
"""


def current(con, dataset_name: str) -> StoredContract | None:
    """The contract in force for a dataset, or None."""
    _ensure_table(con)
    row = con.execute(
        f"{_SELECT} WHERE dataset_name = ? AND is_current ORDER BY version DESC",
        [dataset_name],
    ).fetchone()
    return _row_to_stored(row) if row else None


def history(con, dataset_name: str) -> list[StoredContract]:
    """Every version ever confirmed, newest first."""
    _ensure_table(con)
    rows = con.execute(
        f"{_SELECT} WHERE dataset_name = ? ORDER BY version DESC", [dataset_name]
    ).fetchall()
    return [_row_to_stored(r) for r in rows]


def all_current(con) -> list[StoredContract]:
    """The contract in force for every dataset that has one."""
    _ensure_table(con)
    rows = con.execute(
        f"{_SELECT} WHERE is_current ORDER BY dataset_name"
    ).fetchall()
    return [_row_to_stored(r) for r in rows]


def confirm(
    con, contract: DatasetContract, *, now: datetime | None = None
) -> StoredContract:
    """
    Store a contract as the one in force, closing whatever it replaces.

    `now` is injectable so a test can assert on the SCD2 spans without
    sleeping. Everywhere else it is the wall clock.

    Returns the stored record, with `version` and `confirmed_at` filled in --
    which the caller should hand back to the user, because the version number
    is the thing a later "what did we agree" question is asked about.
    """
    if not contract.is_confirmable:
        raise ContractRefused(contract.blocking_message())

    if contract.bound_to is None:
        raise ContractRefused(
            Refusal(
                reason=Reason.CONTRACT_INVALID,
                what=(
                    f"the contract for '{contract.dataset_name}' has no binding "
                    f"and cannot be confirmed."
                ),
                why=(
                    "a stored contract records the table it was agreed against, "
                    "so that a later reload can be detected. Without it nothing "
                    "can ever tell whether the agreement still holds."
                ),
                detail=(
                    "That drafts one against the loaded table; confirm what it returns."
                ),
                next_call=(
                    f'propose_dataset_contract(dataset_name='
                    f'"{contract.dataset_name}")'
                ),
            ).to_text()
        )

    _ensure_table(con)
    stamp = now or datetime.now()
    live = current(con, contract.dataset_name)

    if live and _comparable(live.contract) == _comparable(contract):
        # Identical to what is already in force. Versions are for changes.
        return live

    version = (live.version + 1) if live else 1
    stored = contract.model_copy(update={"version": version, "confirmed_at": stamp})

    con.begin()
    try:
        if live:
            con.execute(
                f"""UPDATE {CONTRACT_TABLE}
                    SET valid_to = ?, is_current = FALSE
                    WHERE dataset_name = ? AND is_current""",
                [stamp, contract.dataset_name],
            )
        con.execute(
            f"""INSERT INTO {CONTRACT_TABLE} VALUES (?,?,?,?,?,?,?,?,?,?)""",
            [
                stored.dataset_name,
                version,
                stored.model_dump_json(),
                stored.bound_to.fingerprint,
                stored.bound_to.row_count,
                stored.grain,
                stamp,
                stamp,
                None,
                True,
            ],
        )
        con.commit()
    except Exception:
        con.rollback()
        raise

    return StoredContract(
        contract=stored,
        version=version,
        fingerprint=stored.bound_to.fingerprint,
        row_count=stored.bound_to.row_count,
        confirmed_at=stamp,
        valid_from=stamp,
        valid_to=None,
        is_current=True,
    )


def export_path(dataset_name: str, root: Path | str = EXPORT_DIR) -> Path:
    return Path(root) / f"{dataset_name}.yaml"


def write_export(
    contract: DatasetContract, root: Path | str = EXPORT_DIR
) -> Path:
    """
    Write the git-visible copy. Returns the path.

    Imported inside the function so that pyyaml is only needed by whoever
    confirms a contract -- nothing in the ingest path should acquire a
    dependency because the contract layer wanted one.
    """
    import yaml

    path = export_path(contract.dataset_name, root)
    path.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(
        contract.to_yaml_dict(),
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        width=100,
    )
    path.write_text(_EXPORT_HEADER.format(table=CONTRACT_TABLE) + body)
    return path


def history_text(con, dataset_name: str) -> str:
    """Every version, newest first, with what each one changed."""
    rows = history(con, dataset_name)
    if not rows:
        return f"No contract has ever been confirmed for '{dataset_name}'."

    out = [f"{dataset_name}: {len(rows)} version(s)"]
    for i, row in enumerate(rows):
        out.append(f"  {row.line()}")
        older = rows[i + 1] if i + 1 < len(rows) else None
        if older:
            fields = changed_fields(row.contract, older.contract)
            out.append(
                f"      changed: {', '.join(fields) if fields else '(nothing tracked)'}"
            )
    return "\n".join(out)


def summarise(
    stored: StoredContract,
    export: Path | None = None,
    previous: DatasetContract | None = None,
) -> str:
    """What confirm_dataset_contract says back."""
    lines = [
        f"Contract stored for {stored.dataset_name}, version {stored.version}.",
        "",
        stored.contract.to_text(),
        "",
        f"Bound to fingerprint {stored.fingerprint} at "
        f"{stored.row_count:,} rows. Reloading this dataset with different "
        f"columns will be detected; more rows will be noted rather than "
        f"blocking.",
    ]
    if export:
        lines.append(f"Exported to {export} for version control.")
    if stored.version > 1:
        lines.append(
            f"Version {stored.version - 1} was superseded, not replaced -- "
            f"get_workflow_state shows the history."
        )
        if previous is not None:
            fields = changed_fields(stored.contract, previous)
            if fields:
                lines.append(f"Changed since v{stored.version - 1}: {', '.join(fields)}.")
    return "\n".join(lines)


__all__ = [
    "CONTRACT_TABLE",
    "changed_fields",
    "history_text",
    "EXPORT_DIR",
    "StoredContract",
    "all_current",
    "confirm",
    "current",
    "export_path",
    "history",
    "summarise",
    "write_export",
]
